const express = require('express');
const Joi = require('joi');
const ZKProofService = require('../services/ZKProofService');

const router = express.Router();

// ─── Proof generation moved server-side ──────────────────────────────────────
// ZK proofs are now generated inside /api/workflow/process (server-side) and
// stored in the session. They are never sent to or generated by the browser.
//
// The /generate and /generate-batch endpoints are retired.
// Any caller that hits them gets a 410 Gone with a clear migration message.
// ─────────────────────────────────────────────────────────────────────────────

const RETIRED_MESSAGE =
    'This endpoint has been retired. ZK proofs are now generated server-side ' +
    'during POST /api/workflow/process. The proofs are stored in the server ' +
    'session and applied automatically during POST /api/workflow/deploy. ' +
    'No client-side proof generation is needed or supported.';

/**
 * @route POST /api/zkproofs/generate
 * @deprecated Retired — proofs generated server-side in /api/workflow/process
 */
router.post('/generate', (_req, res) => {
    res.status(410).json({ success: false, error: 'Endpoint retired', message: RETIRED_MESSAGE });
});

/**
 * @route POST /api/zkproofs/generate-batch
 * @deprecated Retired — proofs generated server-side in /api/workflow/process
 */
router.post('/generate-batch', (_req, res) => {
    res.status(410).json({ success: false, error: 'Endpoint retired', message: RETIRED_MESSAGE });
});

/**
 * @route POST /api/zkproofs/verify
 * @desc Verify a ZK proof against the stored verification key
 */
router.post('/verify', async (req, res) => {
    try {
        const verificationSchema = Joi.object({
            proof: Joi.object({
                pi_a: Joi.array().items(Joi.string()).length(3).required(),
                pi_b: Joi.array().items(Joi.array().items(Joi.string()).length(2)).length(3).required(),
                pi_c: Joi.array().items(Joi.string()).length(3).required(),
                protocol: Joi.string().default('groth16')
            }).required(),
            publicSignals: Joi.array().items(Joi.string()).required()
        });

        const { error, value } = verificationSchema.validate(req.body);
        if (error) {
            return res.status(400).json({ error: 'Validation Error', details: error.details });
        }

        const isValid = await ZKProofService.verifyProof(value.proof, value.publicSignals);
        res.status(200).json({
            success: true,
            valid: isValid,
            message: isValid ? 'ZK proof is valid' : 'ZK proof verification failed'
        });
    } catch (error) {
        console.error('ZK proof verification error:', error);
        res.status(500).json({ error: 'ZK Proof Verification Failed', message: error.message });
    }
});

/**
 * @route GET /api/zkproofs/circuit-info
 * @desc Returns circuit readiness status and configuration
 */
router.get('/circuit-info', (req, res) => {
    try {
        res.status(200).json({ success: true, data: ZKProofService.getCircuitInfo() });
    } catch (error) {
        res.status(500).json({ error: 'Failed to get circuit information', message: error.message });
    }
});

/**
 * @route POST /api/zkproofs/setup
 * @desc Initialise the proving system (run once before first use)
 */
router.post('/setup', async (req, res) => {
    try {
        const setupResult = await ZKProofService.initializeProvingSystem();
        res.status(200).json({
            success: true,
            message: 'ZK proving system initialised',
            data: setupResult
        });
    } catch (error) {
        res.status(500).json({ error: 'ZK Setup Failed', message: error.message });
    }
});

/**
 * @route GET /api/zkproofs/verification-key
 * @desc Return the Groth16 verification key for contract deployment
 */
router.get('/verification-key', (req, res) => {
    try {
        const verificationKey = ZKProofService.getVerificationKey();
        res.status(200).json({
            success: true,
            data: {
                verificationKey,
                instructions: 'Use this key to deploy the on-chain verifier contract'
            }
        });
    } catch (error) {
        res.status(500).json({ error: 'Failed to get verification key', message: error.message });
    }
});

module.exports = router;