
/**
 * @title IVerifier
 * @dev Interface for the Groth16 verifier generated by snarkjs from
 *      certificate_simple.circom.
 *
 *      The circuit has nPublic = 4 (IC array length = 5):
 *        pubSignals[0] = isValid      (output — circom outputs are public)
 *        pubSignals[1] = commitment   (output — circom outputs are public)
 *        pubSignals[2] = minPassingGrade
 *        pubSignals[3] = requireAllPassed
 *
 *      FIX: was uint[1] — caused ABI mismatch with the snarkjs-generated
 *      verifier which uses uint[4] matching nPublic in verification_key.json.
 */
interface IVerifier {
    function verifyProof(
        uint[2] calldata _pA,
        uint[2][2] calldata _pB,
        uint[2] calldata _pC,
        uint[4] calldata _pubSignals
    ) external view returns (bool);
}
   